# Generated by Django 5.2.5 on 2025-08-29 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message="User Name должен содержать буквы (латиница/кириллица), цифры, пробелы и _-.'.", regex="^[A-Za-z0-9А-Яа-яЁё _\\-.']+$")]),
        ),
    ]
