# Generated by Django 5.2.5 on 2025-08-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_attachment_size_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
